# Generated by Django 6.0.3 on 2026-04-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_options_todo_created_at_todo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
    ]
